name: devnet-ci

on:
  pull_request:
    branches:
      - devnet

jobs:
  build_test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      
    - name: Build Go-WEMIX
      run: USE_ROCKSDB=YES make gwemix.tar.gz

    - name: Stat Go-WEMIX
      run: |
        ls -l build/gwemix.tar.gz
        tar tf build/gwemix.tar.gz

    - name: Move results to artifact
      run: mv build/gwemix.tar.gz gwemix-${{ github.event.pull_request.head.sha }}-linux-rocksdb.tar.gz

    - name: Upload Go-WEMIX
      uses: actions/upload-artifact@v4
      with:
        name: artifact-${{ github.event.pull_request.head.sha }}
        path: gwemix-${{ github.event.pull_request.head.sha }}-linux-rocksdb.tar.gz
        retention-days: 7

  lint_test:
    strategy:
      fail-fast: false
      matrix:
        version: [1.17, 1.18, 1.19]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.version }}
      
    - name: Check Lint
      run: make lint

  unit_test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Check golang Test Cases 
      run: |
        unset ANDROID_HOME
        make test
